// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type AwsEbsVolumeEntityModel struct {
	EntityUuid        types.String `tfsdk:"entity_uuid"`
	EntityName        types.String `tfsdk:"entity_name"`
	EntityType        types.String `tfsdk:"entity_type"`
	CurrentType       types.String `tfsdk:"current_type"`
	NewType           types.String `tfsdk:"new_type"`
	DefaultType       types.String `tfsdk:"default_type"`
	CurrentIops       types.Int64  `tfsdk:"current_iops"`
	NewIops           types.Int64  `tfsdk:"new_iops"`
	DefaultIops       types.Int64  `tfsdk:"default_iops"`
	CurrentThroughput types.Int64  `tfsdk:"current_throughput"`
	NewThroughput     types.Int64  `tfsdk:"new_throughput"`
	DefaultThroughput types.Int64  `tfsdk:"default_throughput"`
	CurrentSize       types.Int64  `tfsdk:"current_size"`
	NewSize           types.Int64  `tfsdk:"new_size"`
	DefaultSize       types.Int64  `tfsdk:"default_size"`
}

type AwsEbsVolumeDataSource struct {
	client *turboclient.Client
}

func NewAwsEbsVolumeDataSource() datasource.DataSource {
	return &AwsEbsVolumeDataSource{}
}

func (d *AwsEbsVolumeDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_aws_ebs_volume"
}

func (d *AwsEbsVolumeDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_aws_ebs_volume` volume source. It uses Turbonomic engine to recommend AWS EBS volume type. For more info, see the [ebs documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume).",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "turbonomic uuid of the volume entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the volume entity",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the volume entity",
				Computed:            true,
			},

			"current_type": schema.StringAttribute{
				MarkdownDescription: "current type of the volume entity",
				Computed:            true,
			},

			"new_type": schema.StringAttribute{
				MarkdownDescription: "recommended type of the volume entity",
				Computed:            true,
			},

			"default_type": schema.StringAttribute{
				MarkdownDescription: "default type of the volume entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOfCaseInsensitive("standard", "gp2", "gp3", "io1", "io2", "sc1", "st1"),
				},
			},

			"current_iops": schema.Int64Attribute{
				MarkdownDescription: "current IOPS of the volume entity, update is only valid for type of io1, io2 or gp3",
				Computed:            true,
			},

			"new_iops": schema.Int64Attribute{
				MarkdownDescription: "recommended IOPS of the volume entity, update is only valid for type of io1, io2 or gp3",
				Computed:            true,
			},

			"default_iops": schema.Int64Attribute{
				MarkdownDescription: "default IOPS of the volume entity, update is only valid for type of io1, io2 or gp3",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(100, 256000),
				},
			},

			"current_throughput": schema.Int64Attribute{
				MarkdownDescription: "current throughput of the volume entity in MiB/s, update is only valid for type of gp3",
				Computed:            true,
			},

			"new_throughput": schema.Int64Attribute{
				MarkdownDescription: "recommended throughput of the volume entity in MiB/s, update is only valid for type of gp3",
				Computed:            true,
			},

			"default_throughput": schema.Int64Attribute{
				MarkdownDescription: "default throughput of the volume entity in MiB/s, update is only valid for type of gp3",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(125, 1000),
				},
			},

			"current_size": schema.Int64Attribute{
				MarkdownDescription: "current size of the volume entity in GiB",
				Computed:            true,
			},

			"new_size": schema.Int64Attribute{
				MarkdownDescription: "recommended size of the volume entity in GiB",
				Computed:            true,
			},

			"default_size": schema.Int64Attribute{
				MarkdownDescription: "default size of the volume entity in GiB",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
		},
	}
}

func (d *AwsEbsVolumeDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.RequiredTogether(
			path.MatchRoot("default_type"),
			path.MatchRoot("default_iops"),
			path.MatchRoot("default_throughput"),
			path.MatchRoot("default_size"),
		),
	}
}

func (d *AwsEbsVolumeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected: *turboclient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *AwsEbsVolumeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state AwsEbsVolumeEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("VirtualVolume")

	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()
	entity, errDiag := GetEntitiesByNameAndType(d.client, enName, enTyp, "CLOUD", "AWS")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(entity) == 0 {
		errDetail := fmt.Sprintf("Entity %s of type %s not found in Turbonomic instance", enName, enTyp)
		tflog.Warn(ctx, errDetail)

		// if entity doesn't exist, update new values with default values
		setDefaultsAwsEbsVolumeToNewState(&state)

		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Entity id found: %s\n", entity[0].UUID))
	state.EntityUuid = types.StringValue(entity[0].UUID)

	// sets current fields in state
	var err error
	state, err = HandleAwsEbsVolumeCurrentState(ctx, state, entity)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for current value",
			err.Error(),
		)
		return
	}
	//as stat returns current value as projected when there are no action.calling it before  checking action to ensure data is available
	commodityActions, errDiag := GetStatsByEntityUUID(d.client, entity[0].UUID)
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	}

	// Use the extracted function to handle commodity actions
	if err := HandleAwsEbsVolumeCommodityAction(ctx, commodityActions, &state); err != nil {
		tflog.Error(ctx, err.Error())
		resp.Diagnostics.AddError("Error while processing commodity actions", err.Error())
		return
	}

	actions, errDiag := GetActionsByEntityUUIDAndType(d.client, entity[0].UUID, "SCALE")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(actions) == 0 {
		errDetail := fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
		tflog.Trace(ctx, errDetail)

		// if action doesn't exist, update new with current value
		setCurrentAwsEbsVolumeToNewState(&state)

		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
		}

		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Action id found: %d\n", actions[0].ActionID))

	state, err = HandleAwsEbsVolumeAction(ctx, resp, state, actions)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for new value",
			err.Error(),
		)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsAwsEbsVolumeToCurrentState(&state)
	setDefaultsAwsEbsVolumeToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
