// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by provider-code-generator

package provider

import (
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

const (
	awsConfig = `
	data "turbonomic_aws_instance" "test" {
		entity_name  = "%s"
		default_instance_type = "%s"
	}
	`
	awsConfigNoDefaultType = `
	data "turbonomic_aws_instance" "test" {
		entity_name  = "%s"
	}
	`
	awsVMDataSourceRef = "data.turbonomic_aws_instance.test"
	awsVMName          = "testVM"
	awsVMCurrentType   = "t2.micro"
	awsVMDefaultType   = "t3a.micro"
	awsVMInvalidType   = "invalid@type#"
)

// Test for a valid entity
func TestAwsInstanceDataSourceWithValidEntity(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, awsVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, awsVMTestDataBaseDir, validVmActionRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagsRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagRespTestData))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "Valid VM recommendation",
			testEntity:          awsVMName,
			expectedEntityName:  awsVMName,
			expectedDefaultType: awsVMDefaultType,
			expectedCurrentType: awsVMCurrentType,
			expectedNewType:     awsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(awsConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "current_instance_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "default_instance_type", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "new_instance_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Test for an invalid entity
func TestAwsInstanceDataSourceWithInvalidEntity(t *testing.T) {
	mockServer := createLocalServer(t, "[]", "", "", "")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedNewType     string
	}{
		{
			name:                "Empty VM search",
			testEntity:          awsVMName,
			expectedEntityName:  awsVMName,
			expectedDefaultType: awsVMDefaultType,
			expectedNewType:     awsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(awsConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckNoResourceAttr(awsVMDataSourceRef, "entity_type"),
							resource.TestCheckNoResourceAttr(awsVMDataSourceRef, "current_instance_type"),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "new_instance_type", tc.expectedNewType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "default_instance_type", tc.expectedDefaultType),
						),
					},
				},
			})
		})
	}
}

// Test for an entity that has no actions
func TestAwsInstanceDataSourceWithNoAction(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, awsVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, emptyActionRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagsRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagRespTestData))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedEntityType  string
		expectedCurrentType string
		expectedNewType     string
		expectedDefaultType string
	}{
		{
			name:                "Empty VM recommendation",
			testEntity:          awsVMName,
			expectedEntityName:  awsVMName,
			expectedDefaultType: awsVMDefaultType,
			expectedCurrentType: awsVMCurrentType,
			expectedNewType:     awsVMCurrentType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(awsConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "current_instance_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "default_instance_type", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "new_instance_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests when default_instance_type is not specified
func TestAwsInstanceDataSourceWithoutDefaultType(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, awsVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, awsVMTestDataBaseDir, validVmActionRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagsRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagRespTestData))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "default_instance_type not specified",
			testEntity:          awsVMName,
			expectedEntityName:  awsVMName,
			expectedCurrentType: awsVMCurrentType,
			expectedNewType:     awsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(awsConfigNoDefaultType, tc.testEntity),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "current_instance_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "new_instance_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests error while retrieving entity tags
func TestAwsInstanceDataSourceGetEntityTagsError(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, awsVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, awsVMTestDataBaseDir, validVmActionRespTestData),
		"",
		"")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	t.Run("Error while retrieving entity tags", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(awsConfig, awsVMName, awsVMDefaultType),
					ExpectError: regexp.MustCompile(`Unable to retrieve entity tags from Turbonomic`),
				},
			},
		})
	})
}

// Tests error while tagging an entity
func TestAwsInstanceDataSourceTagEntityError(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, awsVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, awsVMTestDataBaseDir, validVmActionRespTestData),
		"[]",
		"")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	t.Run("Error while tagging an entity", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(awsConfig, awsVMName, awsVMDefaultType),
					ExpectError: regexp.MustCompile(`Unable to tag an entity in Turbonomic`),
				},
			},
		})
	})
}

// Tests no error while tagging already tagged entity with discovered "optimized by" tag value
func TestAwsInstanceDataSourceTagEntityAlreadyTaggedDiscovered(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, awsVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, awsVMTestDataBaseDir, validVmActionRespTestData),
		`[{"key": "turbonomic_optimized_by","values": ["turbonomic-terraform-provider"]}]`,
		"")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
		expectedDefaultType string
	}{
		{
			name:                "No error while tagging already tagged entity",
			testEntity:          awsVMName,
			expectedEntityName:  awsVMName,
			expectedCurrentType: awsVMCurrentType,
			expectedNewType:     awsVMDefaultType,
			expectedDefaultType: awsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(awsConfig, awsVMName, awsVMDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "current_instance_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "new_instance_type", tc.expectedNewType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "default_instance_type", tc.expectedDefaultType),
						),
					},
				},
			})
		})
	}
}

// Tests no error while tagging already tagged entity with not discovered "optimized by" tag value
func TestAwsInstanceDataSourceTagEntityAlreadyTaggedNotDiscovered(t *testing.T) {
	mockServer := createLocalServerWithResponse(t,
		loadTestFile(t, awsVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, awsVMTestDataBaseDir, validVmActionRespTestData),
		`[]`,
		Response{
			Message:    "Entity service RPC call failed to complete request: INVALID_ARGUMENT: Trying to insert a tag with a key that already exists: turbonomic_optimized_by",
			HttpStatus: http.StatusBadRequest})
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
		expectedDefaultType string
	}{
		{
			name:                "Error while tagging already tagged entity",
			testEntity:          awsVMName,
			expectedEntityName:  awsVMName,
			expectedCurrentType: awsVMCurrentType,
			expectedNewType:     awsVMDefaultType,
			expectedDefaultType: awsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(awsConfig, awsVMName, awsVMDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "current_instance_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "new_instance_type", tc.expectedNewType),
							resource.TestCheckResourceAttr(awsVMDataSourceRef, "default_instance_type", tc.expectedDefaultType),
						),
					},
				},
			})
		})
	}
}

// Tests invalid characters in default_instance_type field
func TestAwsInstanceDataSourceInvalidDefaultTypeCharacters(t *testing.T) {
	t.Run("Invalid characters in default_instance_type", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(awsConfig, awsVMName, awsVMInvalidType),
					ExpectError: regexp.MustCompile(`Invalid Attribute Value Match`),
				},
			},
		})
	})
}
