// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type AwsDbInstanceEntityModel struct {
	EntityUuid           types.String `tfsdk:"entity_uuid"`
	EntityName           types.String `tfsdk:"entity_name"`
	EntityType           types.String `tfsdk:"entity_type"`
	CurrentInstanceClass types.String `tfsdk:"current_instance_class"`
	NewInstanceClass     types.String `tfsdk:"new_instance_class"`
	DefaultInstanceClass types.String `tfsdk:"default_instance_class"`
	CurrentStorageType   types.String `tfsdk:"current_storage_type"`
	NewStorageType       types.String `tfsdk:"new_storage_type"`
	DefaultStorageType   types.String `tfsdk:"default_storage_type"`
}

type AwsDbInstanceDataSource struct {
	client *turboclient.Client
}

func NewAwsDbInstanceDataSource() datasource.DataSource {
	return &AwsDbInstanceDataSource{}
}

func (d *AwsDbInstanceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_aws_db_instance"
}

func (d *AwsDbInstanceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_aws_db_instance` data source.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the AWS RDS entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the AWS RDS entity",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the AWS RDS entity",
				Computed:            true,
			},

			"current_instance_class": schema.StringAttribute{
				MarkdownDescription: "current instance class of the AWS RDS entity",
				Computed:            true,
			},

			"new_instance_class": schema.StringAttribute{
				MarkdownDescription: "recommended instance class of the AWS RDS entity",
				Computed:            true,
			},

			"default_instance_class": schema.StringAttribute{
				MarkdownDescription: "default instance class of the AWS RDS entity",
				Optional:            true,
			},

			"current_storage_type": schema.StringAttribute{
				MarkdownDescription: "current storage type of the AWS RDS entity",
				Computed:            true,
			},

			"new_storage_type": schema.StringAttribute{
				MarkdownDescription: "recommended storage type of the AWS RDS entity",
				Computed:            true,
			},

			"default_storage_type": schema.StringAttribute{
				MarkdownDescription: "default storage type of the AWS RDS entity",
				Optional:            true,
			},
		},
	}
}

func (d *AwsDbInstanceDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.RequiredTogether(
			path.MatchRoot("default_instance_class"),
			path.MatchRoot("default_storage_type"),
		),
	}
}

func (d *AwsDbInstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected: *turboclient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *AwsDbInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state AwsDbInstanceEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("DatabaseServer")

	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()
	entity, errDiag := GetEntitiesByNameAndType(d.client, enName, enTyp, "CLOUD", "AWS")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(entity) == 0 {
		errDetail := fmt.Sprintf("Entity %s of type %s not found in Turbonomic instance", enName, enTyp)
		tflog.Warn(ctx, errDetail)

		// if entity doesn't exist, update new values with default values
		state.NewInstanceClass = applyDefaultIfEmpty(
			state.NewInstanceClass,
			state.DefaultInstanceClass,
		)
		state.NewStorageType = applyDefaultIfEmpty(
			state.NewStorageType,
			state.DefaultStorageType,
		)

		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Entity id found: %s\n", entity[0].UUID))
	state.EntityUuid = types.StringValue(entity[0].UUID)

	// sets current fields in state
	var err error
	state, err = HandleAwsDbInstanceCurrentState(ctx, state, entity)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for current value",
			err.Error(),
		)
		return
	}

	actions, errDiag := GetActionsByEntityUUIDAndType(d.client, entity[0].UUID, "SCALE")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(actions) == 0 {
		errDetail := fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
		tflog.Trace(ctx, errDetail)

		// if action doesn't exist, update new with current value
		state.NewInstanceClass = state.CurrentInstanceClass
		state.NewStorageType = state.CurrentStorageType

		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
		}

		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Action id found: %d\n", actions[0].ActionID))

	state, err = HandleAwsDbInstanceAction(ctx, resp, state, actions)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for new value",
			err.Error(),
		)
		return
	}

	// update new and curr values with default values, if its still empty
	state.CurrentInstanceClass = applyDefaultIfEmpty(
		state.CurrentInstanceClass,
		state.DefaultInstanceClass,
	)
	state.NewInstanceClass = applyDefaultIfEmpty(
		state.NewInstanceClass,
		state.DefaultInstanceClass,
	)
	state.CurrentStorageType = applyDefaultIfEmpty(
		state.CurrentStorageType,
		state.DefaultStorageType,
	)
	state.NewStorageType = applyDefaultIfEmpty(
		state.NewStorageType,
		state.DefaultStorageType,
	)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
