// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.
// This file will be overwritten by the generator.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type AwsDbInstanceEntityModel struct {
	EntityUuid              types.String `tfsdk:"entity_uuid"`
	EntityName              types.String `tfsdk:"entity_name"`
	EntityType              types.String `tfsdk:"entity_type"`
	CurrentInstanceClass    types.String `tfsdk:"current_instance_class"`
	NewInstanceClass        types.String `tfsdk:"new_instance_class"`
	DefaultInstanceClass    types.String `tfsdk:"default_instance_class"`
	CurrentStorageType      types.String `tfsdk:"current_storage_type"`
	NewStorageType          types.String `tfsdk:"new_storage_type"`
	DefaultStorageType      types.String `tfsdk:"default_storage_type"`
	CurrentIops             types.Int64  `tfsdk:"current_iops"`
	NewIops                 types.Int64  `tfsdk:"new_iops"`
	DefaultIops             types.Int64  `tfsdk:"default_iops"`
	CurrentAllocatedStorage types.Int64  `tfsdk:"current_allocated_storage"`
	NewAllocatedStorage     types.Int64  `tfsdk:"new_allocated_storage"`
	DefaultAllocatedStorage types.Int64  `tfsdk:"default_allocated_storage"`
}

type AwsDbInstanceDataSource struct {
	client *turboclient.Client
}

func NewAwsDbInstanceDataSource() datasource.DataSource {
	return &AwsDbInstanceDataSource{}
}

func (d *AwsDbInstanceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_aws_db_instance"
}

func (d *AwsDbInstanceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_aws_db_instance` data source.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the AWS RDS entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the AWS RDS entity",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the AWS RDS entity",
				Computed:            true,
			},

			"current_instance_class": schema.StringAttribute{
				MarkdownDescription: "current instance class of the AWS RDS entity",
				Computed:            true,
			},

			"new_instance_class": schema.StringAttribute{
				MarkdownDescription: "recommended instance class of the AWS RDS entity",
				Computed:            true,
			},

			"default_instance_class": schema.StringAttribute{
				MarkdownDescription: "default instance class of the AWS RDS entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"current_storage_type": schema.StringAttribute{
				MarkdownDescription: "current storage type of the AWS RDS entity",
				Computed:            true,
			},

			"new_storage_type": schema.StringAttribute{
				MarkdownDescription: "recommended storage type of the AWS RDS entity",
				Computed:            true,
			},

			"default_storage_type": schema.StringAttribute{
				MarkdownDescription: "default storage type of the AWS RDS entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"current_iops": schema.Int64Attribute{
				MarkdownDescription: "current IOPS of the AWS RDS entity, update is only valid for type of io1, io2 or gp3",
				Computed:            true,
			},

			"new_iops": schema.Int64Attribute{
				MarkdownDescription: "recommended IOPS of the AWS RDS entity, update is only valid for type of io1, io2 or gp3",
				Computed:            true,
			},

			"default_iops": schema.Int64Attribute{
				MarkdownDescription: "default IOPS of the AWS RDS entity, update is only valid for type of io1, io2 or gp3",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},

			"current_allocated_storage": schema.Int64Attribute{
				MarkdownDescription: "current allocated storage of the AWS RDS entity in GiB",
				Computed:            true,
			},

			"new_allocated_storage": schema.Int64Attribute{
				MarkdownDescription: "recommended allocated storage of the AWS RDS entity in GiB",
				Computed:            true,
			},

			"default_allocated_storage": schema.Int64Attribute{
				MarkdownDescription: "default allocated storage of the AWS RDS entity in GiB",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
		},
	}
}

func (d *AwsDbInstanceDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.RequiredTogether(
			path.MatchRoot("default_instance_class"),
			path.MatchRoot("default_storage_type"),
			path.MatchRoot("default_iops"),
			path.MatchRoot("default_allocated_storage"),
		),
	}
}

func (d *AwsDbInstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("expected: *turboclient.Client, got: %T. please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *AwsDbInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state AwsDbInstanceEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("DatabaseServer")
	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()

	if d.client == nil {
		// set new values with default values, if client is unset/unreachable
		setDefaultsAwsDbInstanceToNewState(&state)
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	var entity turboclient.SearchResults
	var errDiag *diag.ErrorDiagnostic
	entityArgs := []EntityOption{
		WithEntityName(enName),
		WithEntityType(enTyp),
		WithEnvironmentType("CLOUD"),
		WithCloudType("AWS"),
	}
	entity, errDiag = GetEntitiesByName(d.client, entityArgs...)

	var err error
	var errDetail string
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(entity) == 0 {
		errDetail = fmt.Sprintf("entity %s of type %s not found in Turbonomic instance", enName, enTyp)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("entity id found: %s\n", entity[0].UUID))
		state.EntityUuid = types.StringValue(entity[0].UUID)
		state, err = HandleAwsDbInstanceCurrentState(ctx, state, entity)
		if err != nil {
			errDetail = fmt.Sprintf("error while trying to retrieve current value, %s", err.Error())
		}
	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an entity", errDetail)

		// if entity doesn't exist or got an error while retrieving entity using API, update new values with default values
		setDefaultsAwsDbInstanceToNewState(&state)
		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}
	// as stat returns current value as projected when there are no action, calling it before  checking action to ensure data is available
	commodityActions, errDiag := GetStatsByEntityUUIDAndType(d.client, entity[0].UUID, "DatabaseServer")
	if errDiag != nil {
		tflog.Warn(ctx, errDiag.Detail())
		resp.Diagnostics.AddWarning(errDiag.Summary(), errDiag.Detail())
		return
	}

	// use the extracted function to handle commodity actions
	if err := HandleAwsDbInstanceCommodityAction(ctx, commodityActions, &state); err != nil {
		tflog.Warn(ctx, err.Error())
		resp.Diagnostics.AddWarning("error while processing commodity actions", err.Error())
		return
	}

	actions, errDiag := GetActions(d.client, WithEntityUuid(entity[0].UUID), WithActionTypes([]string{"SCALE"}))
	errDetail = ""
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(actions) == 0 {
		errDetail = fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("action id found: %d\n", actions[0].ActionID))

		canExecute, executeMsg := canExecuteAction(actions)
		if canExecute {
			state, err = HandleAwsDbInstanceAction(ctx, resp, state, actions)
			if err != nil {
				errDetail = fmt.Sprintf("error while trying to retrieve new value, %s", err.Error())
			}
		} else {
			errDetail = executeMsg
		}

	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an action", errDetail)

		// if action doesn't exist or got an error while retrieving entity action using API, update new with current value
		setCurrentAwsDbInstanceToNewState(&state)
		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
		}
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsAwsDbInstanceToCurrentState(&state)
	setDefaultsAwsDbInstanceToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// set the current state fields with default values if they are empty
func setDefaultsAwsDbInstanceToCurrentState(state *AwsDbInstanceEntityModel) {
	state.CurrentInstanceClass = applyDefaultIfEmptyGeneric(state.CurrentInstanceClass, state.DefaultInstanceClass)
	state.CurrentStorageType = applyDefaultIfEmptyGeneric(state.CurrentStorageType, state.DefaultStorageType)
	state.CurrentIops = applyDefaultIfEmptyGeneric(state.CurrentIops, state.DefaultIops)
	state.CurrentAllocatedStorage = applyDefaultIfEmptyGeneric(state.CurrentAllocatedStorage, state.DefaultAllocatedStorage)
}

// set the new state fields with default values if they are empty
func setDefaultsAwsDbInstanceToNewState(state *AwsDbInstanceEntityModel) {
	state.NewInstanceClass = applyDefaultIfEmptyGeneric(state.NewInstanceClass, state.DefaultInstanceClass)
	state.NewStorageType = applyDefaultIfEmptyGeneric(state.NewStorageType, state.DefaultStorageType)
	state.NewIops = applyDefaultIfEmptyGeneric(state.NewIops, state.DefaultIops)
	state.NewAllocatedStorage = applyDefaultIfEmptyGeneric(state.NewAllocatedStorage, state.DefaultAllocatedStorage)
}

// apply current values to new values if action/stat projected value is not available
func setCurrentAwsDbInstanceToNewState(state *AwsDbInstanceEntityModel) {
	state.NewInstanceClass = applyDefaultIfEmptyGeneric(state.NewInstanceClass, state.CurrentInstanceClass)
	state.NewStorageType = applyDefaultIfEmptyGeneric(state.NewStorageType, state.CurrentStorageType)
	state.NewIops = applyDefaultIfEmptyGeneric(state.NewIops, state.CurrentIops)
	state.NewAllocatedStorage = applyDefaultIfEmptyGeneric(state.NewAllocatedStorage, state.CurrentAllocatedStorage)
}
