// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by provider-code-generator

package provider

import (
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

const (
	azureWindowsVMConfig = `
	data "turbonomic_azurerm_windows_virtual_machine" "test" {
		entity_name  = "%s"
		default_size = "%s"
	}
	`
	azureWindowsVMConfigNoDefaultType = `
	data "turbonomic_azurerm_windows_virtual_machine" "test" {
		entity_name  = "%s"
	}
	`
	azureWindowsVMDataSourceRef = "data.turbonomic_azurerm_windows_virtual_machine.test"
	azureWindowsVMName          = "test-vm"
	azureWindowsVMCurrentType   = "Standard_B1s"
	azureWindowsVMDefaultType   = "Standard_D2s_v3"
)

// Test for a valid entity
func TestAzurermWindowsVirtualMachineDataSourceWithValidEntity(t *testing.T) {
	mockServer := mockTurboServer(t, append([]MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
	}, LoginAndTagRoutes(t)...))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "Valid VM recommendation",
			testEntity:          azureWindowsVMName,
			expectedEntityName:  azureWindowsVMName,
			expectedDefaultType: azureWindowsVMDefaultType,
			expectedCurrentType: azureWindowsVMCurrentType,
			expectedNewType:     azureWindowsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(azureWindowsVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "default_size", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "current_size", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Test for an invalid entity
func TestAzurermWindowsVirtualMachineDataSourceWithInvalidEntity(t *testing.T) {
	mockServer := mockTurboServer(t, []MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: "[]",
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: "",
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/login",
			ResponseCode: http.StatusOK,
			ResponseBody: `{"status":"ok"}`,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "",
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodGet,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "",
			ResponseCode: http.StatusOK,
		},
	})

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedNewType     string
	}{
		{
			name:                "Empty VM search",
			testEntity:          azureWindowsVMName,
			expectedEntityName:  azureWindowsVMName,
			expectedDefaultType: azureWindowsVMDefaultType,
			expectedNewType:     azureWindowsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(azureWindowsVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckNoResourceAttr(azureWindowsVMDataSourceRef, "entity_type"),
							resource.TestCheckNoResourceAttr(azureWindowsVMDataSourceRef, "current_size"),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", tc.expectedNewType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "default_size", tc.expectedDefaultType),
						),
					},
				},
			})
		})
	}
}

// TODO: Test for an entity that has no actions
func TestAzurermWindowsVirtualMachineDataSourceWithNoAction(t *testing.T) {
	mockServer := mockTurboServer(t, append([]MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, emptyActionRespTestData),
			ResponseCode: http.StatusOK,
		},
	}, LoginAndTagRoutes(t)...))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "Empty VM recommendation",
			testEntity:          azureWindowsVMName,
			expectedEntityName:  azureWindowsVMName,
			expectedDefaultType: azureWindowsVMDefaultType,
			expectedCurrentType: azureWindowsVMCurrentType,
			expectedNewType:     azureWindowsVMCurrentType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(azureWindowsVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "default_size", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "current_size", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests when default_size is not specified
func TestAzurermWindowsVirtualMachineDataSourceWithoutDefaultType(t *testing.T) {
	mockServer := mockTurboServer(t, append([]MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
	}, LoginAndTagRoutes(t)...))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "default_size not specified",
			testEntity:          azureWindowsVMName,
			expectedEntityName:  azureWindowsVMName,
			expectedCurrentType: azureWindowsVMCurrentType,
			expectedNewType:     azureWindowsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(azureWindowsVMConfigNoDefaultType, tc.testEntity),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "current_size", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests no error while retrieving entity tags
func TestAzurermWindowsVirtualMachineDataSourceGetEntityTagsError(t *testing.T) {
	mockServer := mockTurboServer(t, []MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/login",
			ResponseCode: http.StatusOK,
			ResponseBody: `{"status":"ok"}`,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "",
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodGet,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "",
			ResponseCode: http.StatusOK,
		},
	})

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	t.Run("no error while retrieving entity tags", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(azureWindowsVMConfig, azureWindowsVMName, azureWindowsVMDefaultType),
					ExpectError: nil,
				},
			},
		})
	})
}

// Tests no error while tagging an entity
func TestAzurermWindowsVirtualMachineDataSourceTagEntityError(t *testing.T) {
	mockServer := mockTurboServer(t, []MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/login",
			ResponseCode: http.StatusOK,
			ResponseBody: `{"status":"ok"}`,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "",
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodGet,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "[]",
			ResponseCode: http.StatusOK,
		},
	})

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	t.Run("no error while tagging an entity", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(azureWindowsVMConfig, azureWindowsVMName, azureWindowsVMDefaultType),
					ExpectError: nil,
				},
			},
		})
	})
}

// Tests no error while tagging already tagged entity with discovered "optimized by" tag value
func TestAzurermWindowsVirtualMachineDataSourceTagEntityAlreadyTaggedDiscovered(t *testing.T) {
	mockServer := mockTurboServer(t, []MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/login",
			ResponseCode: http.StatusOK,
			ResponseBody: `{"status":"ok"}`,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "",
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodGet,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: `[{"key": "turbonomic_optimized_by","values": ["turbonomic-terraform-provider"]}]`,
			ResponseCode: http.StatusOK,
		},
	})

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
		expectedDefaultType string
	}{
		{
			name:                "No error while tagging already tagged entity",
			testEntity:          azureWindowsVMName,
			expectedEntityName:  azureWindowsVMName,
			expectedCurrentType: azureWindowsVMCurrentType,
			expectedNewType:     azureWindowsVMDefaultType,
			expectedDefaultType: azureWindowsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(azureWindowsVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "default_size", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "current_size", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests no error while tagging already tagged entity with not discovered "optimized by" tag value
func TestAzurermWindowsVirtualMachineDataSourceTagEntityAlreadyTaggedNotDiscovered(t *testing.T) {
	mockServer := mockTurboServer(t, []MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/login",
			ResponseCode: http.StatusOK,
			ResponseBody: `{"status":"ok"}`,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: "Entity service RPC call failed to complete request: INVALID_ARGUMENT: Trying to insert a tag with a key that already exists: turbonomic_optimized_by",
			ResponseCode: http.StatusBadRequest,
		},
		{
			Method:       http.MethodGet,
			Path:         "/api/v3/entities/{id}/tags",
			ResponseBody: `[]`,
			ResponseCode: http.StatusOK,
		},
	})

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
		expectedDefaultType string
	}{
		{
			name:                "Error while tagging already tagged entity",
			testEntity:          azureWindowsVMName,
			expectedEntityName:  azureWindowsVMName,
			expectedCurrentType: azureWindowsVMCurrentType,
			expectedNewType:     azureWindowsVMDefaultType,
			expectedDefaultType: azureWindowsVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(azureWindowsVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "default_size", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "current_size", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests if os name filter is set in request body
func TestAzurermWindowsVirtualMachineDataSourceOSNameFilter(t *testing.T) {
	mockServer := mockTurboServer(t, append([]MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ExpectedBody: `{"criteriaList":[{"caseSensitive":true,"expType":"EQ","expVal":"test-vm","filterType":"vmsByName"},{"caseSensitive":false,"expType":"EQ","expVal":"AZURE","filterType":"vmsByCloudProvider"},{"caseSensitive":false,"expType":"RXEQ","expVal":"windows.*","filterType":"vmsByGuestName"}],"logicalOperator":"AND","className":"VirtualMachine","environmentType":"CLOUD"}`,
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
	}, LoginAndTagRoutes(t)...))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	t.Run("test os filter", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config: providerConfig + fmt.Sprintf(azureWindowsVMConfig, azureWindowsVMName, azureWindowsVMDefaultType),
					Check: resource.ComposeAggregateTestCheckFunc(
						resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", azureWindowsVMDefaultType),
					),
				},
			},
		})
	})
}

// Tests if os name filter fails, entity is still getting searched
func TestAzurermWindowsVirtualMachineDataSourceOSNameFilterErr(t *testing.T) {
	mockServer := mockTurboServer(t, append([]MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ExpectedBody: `{"criteriaList":[{"caseSensitive":true,"expType":"EQ","expVal":"test-vm","filterType":"vmsByName"},{"caseSensitive":false,"expType":"EQ","expVal":"AZURE","filterType":"vmsByCloudProvider"}],"logicalOperator":"AND","className":"VirtualMachine","environmentType":"CLOUD"}`,
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
	}, LoginAndTagRoutes(t)...))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	t.Run("test os filter", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config: providerConfig + fmt.Sprintf(azureWindowsVMConfig, azureWindowsVMName, azureWindowsVMDefaultType),
					Check: resource.ComposeAggregateTestCheckFunc(
						resource.TestCheckResourceAttr(azureWindowsVMDataSourceRef, "new_size", azureWindowsVMDefaultType),
					),
				},
			},
		})
	})
}

func TestAzurermWindowsVirtualMachineDataSourceWithEmptyDefaultType(t *testing.T) {
	mockServer := mockTurboServer(t, append([]MockRoute{
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/search",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, searchRespTestData),
			ResponseCode: http.StatusOK,
		},
		{
			Method:       http.MethodPost,
			Path:         "/api/v3/entities/{id}/actions",
			ResponseBody: loadTestFile(t, azureWindowsVMTestDataBaseDir, validVmActionRespTestData),
			ResponseCode: http.StatusOK,
		},
	}, LoginAndTagRoutes(t)...))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	t.Run("Default machine type should be atleast 1", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(azureWindowsVMConfig, azureWindowsVMName, ""),
					ExpectError: regexp.MustCompile(`Attribute default_size string length must be at least 1`),
				},
			},
		})
	})
}
