// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type AzurermManagedDiskEntityModel struct {
	EntityUuid                types.String `tfsdk:"entity_uuid"`
	EntityName                types.String `tfsdk:"entity_name"`
	EntityType                types.String `tfsdk:"entity_type"`
	CurrentStorageAccountType types.String `tfsdk:"current_storage_account_type"`
	NewStorageAccountType     types.String `tfsdk:"new_storage_account_type"`
	DefaultStorageAccountType types.String `tfsdk:"default_storage_account_type"`
	CurrentDiskIopsReadWrite  types.Int64  `tfsdk:"current_disk_iops_read_write"`
	NewDiskIopsReadWrite      types.Int64  `tfsdk:"new_disk_iops_read_write"`
	DefaultDiskIopsReadWrite  types.Int64  `tfsdk:"default_disk_iops_read_write"`
	CurrentDiskMbpsReadWrite  types.Int64  `tfsdk:"current_disk_mbps_read_write"`
	NewDiskMbpsReadWrite      types.Int64  `tfsdk:"new_disk_mbps_read_write"`
	DefaultDiskMbpsReadWrite  types.Int64  `tfsdk:"default_disk_mbps_read_write"`
	CurrentDiskSizeGb         types.Int64  `tfsdk:"current_disk_size_gb"`
	NewDiskSizeGb             types.Int64  `tfsdk:"new_disk_size_gb"`
	DefaultDiskSizeGb         types.Int64  `tfsdk:"default_disk_size_gb"`
}

type AzurermManagedDiskDataSource struct {
	client *turboclient.Client
}

func NewAzurermManagedDiskDataSource() datasource.DataSource {
	return &AzurermManagedDiskDataSource{}
}

func (d *AzurermManagedDiskDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azurerm_managed_disk"
}

func (d *AzurermManagedDiskDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_azurerm_managed_disk` data source.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the Azure Managed Disk entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the Azure Managed Disk entity",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the Azure Managed Disk entity",
				Computed:            true,
			},

			"current_storage_account_type": schema.StringAttribute{
				MarkdownDescription: "current storage type of the Azure Managed Disk entity",
				Computed:            true,
			},

			"new_storage_account_type": schema.StringAttribute{
				MarkdownDescription: "recommended storage type of the Azure Managed Disk entity",
				Computed:            true,
			},

			"default_storage_account_type": schema.StringAttribute{
				MarkdownDescription: "default storage type of the Azure Managed Disk entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("Standard_LRS", "StandardSSD_LRS", "Premium_LRS", "UltraSSD_LRS", "PremiumV2_LRS", "StandardSSD_ZRS"),
				},
			},

			"current_disk_iops_read_write": schema.Int64Attribute{
				MarkdownDescription: "current IOPS of the volume entity, update is only valid for UltraSSD disks and PremiumV2 disks",
				Computed:            true,
			},

			"new_disk_iops_read_write": schema.Int64Attribute{
				MarkdownDescription: "recommended IOPS of the volume entity, update is only valid for UltraSSD disks and PremiumV2 disks",
				Computed:            true,
			},

			"default_disk_iops_read_write": schema.Int64Attribute{
				MarkdownDescription: "default IOPS of the volume entity, update is only valid for UltraSSD disks and PremiumV2 disks",
				Optional:            true,
			},

			"current_disk_mbps_read_write": schema.Int64Attribute{
				MarkdownDescription: "current throughput of the volume entity in MiB/s",
				Computed:            true,
			},

			"new_disk_mbps_read_write": schema.Int64Attribute{
				MarkdownDescription: "recommended throughput of the volume entity in MiB/s",
				Computed:            true,
			},

			"default_disk_mbps_read_write": schema.Int64Attribute{
				MarkdownDescription: "default throughput of the volume entity in MiB/s",
				Optional:            true,
			},

			"current_disk_size_gb": schema.Int64Attribute{
				MarkdownDescription: "current size of the volume entity in GiB",
				Computed:            true,
			},

			"new_disk_size_gb": schema.Int64Attribute{
				MarkdownDescription: "recommended size of the volume entity in GiB",
				Computed:            true,
			},

			"default_disk_size_gb": schema.Int64Attribute{
				MarkdownDescription: "default size of the volume entity in GiB",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.Between(0, 65536),
				},
			},
		},
	}
}

func (d *AzurermManagedDiskDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.RequiredTogether(
			path.MatchRoot("default_storage_account_type"),
			path.MatchRoot("default_disk_iops_read_write"),
			path.MatchRoot("default_disk_mbps_read_write"),
			path.MatchRoot("default_disk_size_gb"),
		),
	}
}

func (d *AzurermManagedDiskDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected: *turboclient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *AzurermManagedDiskDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state AzurermManagedDiskEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("VirtualVolume")

	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()
	entity, errDiag := GetEntitiesByNameAndType(d.client, enName, enTyp, "CLOUD", "AZURE")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(entity) == 0 {
		errDetail := fmt.Sprintf("Entity %s of type %s not found in Turbonomic instance", enName, enTyp)
		tflog.Warn(ctx, errDetail)

		// if entity doesn't exist, update new values with default values
		setDefaultsAzurermManagedDiskToNewState(&state)

		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Entity id found: %s\n", entity[0].UUID))
	state.EntityUuid = types.StringValue(entity[0].UUID)

	// sets current fields in state
	var err error
	state, err = HandleAzurermManagedDiskCurrentState(ctx, state, entity)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for current value",
			err.Error(),
		)
		return
	}
	//as stat returns current value as projected when there are no action.calling it before  checking action to ensure data is available
	commodityActions, errDiag := GetStatsByEntityUUID(d.client, entity[0].UUID)
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	}

	// Use the extracted function to handle commodity actions
	if err := HandleAzurermManagedDiskCommodityAction(ctx, commodityActions, &state); err != nil {
		tflog.Error(ctx, err.Error())
		resp.Diagnostics.AddError("Error while processing commodity actions", err.Error())
		return
	}

	actions, errDiag := GetActionsByEntityUUIDAndType(d.client, entity[0].UUID, "SCALE")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(actions) == 0 {
		errDetail := fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
		tflog.Trace(ctx, errDetail)

		// if action doesn't exist, update new with current value
		setCurrentAzurermManagedDiskToNewState(&state)

		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
		}

		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Action id found: %d\n", actions[0].ActionID))

	state, err = HandleAzurermManagedDiskAction(ctx, resp, state, actions)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for new value",
			err.Error(),
		)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsAzurermManagedDiskToCurrentState(&state)
	setDefaultsAzurermManagedDiskToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
