// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.
// This file will be overwritten by the generator.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type AzurermMssqlDatabaseEntityModel struct {
	EntityName     types.String `tfsdk:"entity_name"`
	EntityType     types.String `tfsdk:"entity_type"`
	CurrentSkuName types.String `tfsdk:"current_sku_name"`
	NewSkuName     types.String `tfsdk:"new_sku_name"`
	DefaultSkuName types.String `tfsdk:"default_sku_name"`
	EntityUuid     types.String `tfsdk:"entity_uuid"`
}

type AzurermMssqlDatabaseDataSource struct {
	client *turboclient.Client
}

func NewAzurermMssqlDatabaseDataSource() datasource.DataSource {
	return &AzurermMssqlDatabaseDataSource{}
}

func (d *AzurermMssqlDatabaseDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azurerm_mssql_database"
}

func (d *AzurermMssqlDatabaseDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the azurerm_mssql_database data source.",
		Attributes: map[string]schema.Attribute{

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the database entity",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the database entity",
				Computed:            true,
			},

			"current_sku_name": schema.StringAttribute{
				MarkdownDescription: "current sku name of the database entity",
				Computed:            true,
			},

			"new_sku_name": schema.StringAttribute{
				MarkdownDescription: "recommended sku name of the database entity",
				Computed:            true,
			},

			"default_sku_name": schema.StringAttribute{
				MarkdownDescription: "default sku name of the database entity",
				Optional:            true,
			},

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "turbonomic uuid of the entity",
				Computed:            true,
			},
		},
	}
}

func (d *AzurermMssqlDatabaseDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("expected: *turboclient.Client, got: %T. please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *AzurermMssqlDatabaseDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state AzurermMssqlDatabaseEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("Database")
	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()

	if d.client == nil {
		// set new values with default values, if client is unset/unreachable
		setDefaultsAzurermMssqlDatabaseToNewState(&state)
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	var entity turboclient.SearchResults
	var errDiag *diag.ErrorDiagnostic
	entityArgs := []EntityOption{
		WithEntityName(enName),
		WithEntityType(enTyp),
		WithEnvironmentType("CLOUD"),
		WithCloudType("AZURE"),
	}
	entity, errDiag = GetEntitiesByName(d.client, entityArgs...)

	var err error
	var errDetail string
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(entity) == 0 {
		errDetail = fmt.Sprintf("entity %s of type %s not found in Turbonomic instance", enName, enTyp)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("entity id found: %s\n", entity[0].UUID))
		state.EntityUuid = types.StringValue(entity[0].UUID)
		state, err = HandleAzurermMssqlDatabaseCurrentState(ctx, state, entity)
		if err != nil {
			errDetail = fmt.Sprintf("error while trying to retrieve current value, %s", err.Error())
		}
	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an entity", errDetail)

		// if entity doesn't exist or got an error while retrieving entity using API, update new values with default values
		setDefaultsAzurermMssqlDatabaseToNewState(&state)
		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	actions, errDiag := GetActions(d.client, WithEntityUuid(entity[0].UUID), WithActionTypes([]string{"SCALE"}))
	errDetail = ""
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(actions) == 0 {
		errDetail = fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("action id found: %d\n", actions[0].ActionID))

		canExecute, executeMsg := canExecuteAction(actions)
		if canExecute {
			state, err = HandleAzurermMssqlDatabaseAction(ctx, resp, state, actions)
			if err != nil {
				errDetail = fmt.Sprintf("error while trying to retrieve new value, %s", err.Error())
			}
		} else {
			errDetail = executeMsg
		}

	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an action", errDetail)

		// if action doesn't exist or got an error while retrieving entity action using API, update new with current value
		setCurrentAzurermMssqlDatabaseToNewState(&state)
		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
		}
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsAzurermMssqlDatabaseToCurrentState(&state)
	setDefaultsAzurermMssqlDatabaseToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// set the current state fields with default values if they are empty
func setDefaultsAzurermMssqlDatabaseToCurrentState(state *AzurermMssqlDatabaseEntityModel) {
	state.CurrentSkuName = applyDefaultIfEmptyGeneric(state.CurrentSkuName, state.DefaultSkuName)
}

// set the new state fields with default values if they are empty
func setDefaultsAzurermMssqlDatabaseToNewState(state *AzurermMssqlDatabaseEntityModel) {
	state.NewSkuName = applyDefaultIfEmptyGeneric(state.NewSkuName, state.DefaultSkuName)
}

// apply current values to new values if action/stat projected value is not available
func setCurrentAzurermMssqlDatabaseToNewState(state *AzurermMssqlDatabaseEntityModel) {
	state.NewSkuName = applyDefaultIfEmptyGeneric(state.NewSkuName, state.CurrentSkuName)
}
