// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.
// This file will be overwritten by the generator.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type AzurermLinuxVirtualMachineEntityModel struct {
	EntityUuid  types.String `tfsdk:"entity_uuid"`
	EntityName  types.String `tfsdk:"entity_name"`
	EntityType  types.String `tfsdk:"entity_type"`
	CurrentSize types.String `tfsdk:"current_size"`
	NewSize     types.String `tfsdk:"new_size"`
	DefaultSize types.String `tfsdk:"default_size"`
}

type AzurermLinuxVirtualMachineDataSource struct {
	client *turboclient.Client
}

func NewAzurermLinuxVirtualMachineDataSource() datasource.DataSource {
	return &AzurermLinuxVirtualMachineDataSource{}
}

func (d *AzurermLinuxVirtualMachineDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azurerm_linux_virtual_machine"
}

func (d *AzurermLinuxVirtualMachineDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_azurerm_linux_virtual_machine` data source.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the Azure VM entity for Linux",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the Azure VM entity for Linux",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the Azure VM entity for Linux",
				Computed:            true,
			},

			"current_size": schema.StringAttribute{
				MarkdownDescription: "current size of the Azure VM entity for Linux",
				Computed:            true,
			},

			"new_size": schema.StringAttribute{
				MarkdownDescription: "recommended size of the Azure VM entity for Linux",
				Computed:            true,
			},

			"default_size": schema.StringAttribute{
				MarkdownDescription: "default size of the Azure VM entity for Linux",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
		},
	}
}

func (d *AzurermLinuxVirtualMachineDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("expected: *turboclient.Client, got: %T. please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *AzurermLinuxVirtualMachineDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state AzurermLinuxVirtualMachineEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("VirtualMachine")
	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()

	if d.client == nil {
		// set new values with default values, if client is unset/unreachable
		setDefaultsAzurermLinuxVirtualMachineToNewState(&state)
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	var entity turboclient.SearchResults
	var errDiag *diag.ErrorDiagnostic
	entityArgs := []EntityOption{
		WithEntityName(enName),
		WithEntityType(enTyp),
		WithEnvironmentType("CLOUD"),
		WithCloudType("AZURE"),
	}
	entity, errDiag = GetEntitiesByName(d.client, append(entityArgs, WithOSNames("linux", "rhel"))...)
	if errDiag != nil {
		errDetail := fmt.Sprintf("entity %s of type: %s and osNames: %s not found in Turbonomic instance, searching without osNames", enName, enTyp, "[Linux Rhel]")
		tflog.Warn(ctx, errDetail)
		entity, errDiag = GetEntitiesByName(d.client, entityArgs...)
	}

	var err error
	var errDetail string
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(entity) == 0 {
		errDetail = fmt.Sprintf("entity %s of type %s not found in Turbonomic instance", enName, enTyp)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("entity id found: %s\n", entity[0].UUID))
		state.EntityUuid = types.StringValue(entity[0].UUID)
		state, err = HandleAzurermLinuxVirtualMachineCurrentState(ctx, state, entity)
		if err != nil {
			errDetail = fmt.Sprintf("error while trying to retrieve current value, %s", err.Error())
		}
	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an entity", errDetail)

		// if entity doesn't exist or got an error while retrieving entity using API, update new values with default values
		setDefaultsAzurermLinuxVirtualMachineToNewState(&state)
		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	actions, errDiag := GetActions(d.client, WithEntityUuid(entity[0].UUID), WithActionTypes([]string{"SCALE"}))
	errDetail = ""
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(actions) == 0 {
		errDetail = fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("action id found: %d\n", actions[0].ActionID))

		canExecute, executeMsg := canExecuteAction(actions)
		if canExecute {
			state, err = HandleAzurermLinuxVirtualMachineAction(ctx, resp, state, actions)
			if err != nil {
				errDetail = fmt.Sprintf("error while trying to retrieve new value, %s", err.Error())
			}
		} else {
			errDetail = executeMsg
		}

	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an action", errDetail)

		// if action doesn't exist or got an error while retrieving entity action using API, update new with current value
		setCurrentAzurermLinuxVirtualMachineToNewState(&state)
		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
		}
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsAzurermLinuxVirtualMachineToCurrentState(&state)
	setDefaultsAzurermLinuxVirtualMachineToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// set the current state fields with default values if they are empty
func setDefaultsAzurermLinuxVirtualMachineToCurrentState(state *AzurermLinuxVirtualMachineEntityModel) {
	state.CurrentSize = applyDefaultIfEmptyGeneric(state.CurrentSize, state.DefaultSize)
}

// set the new state fields with default values if they are empty
func setDefaultsAzurermLinuxVirtualMachineToNewState(state *AzurermLinuxVirtualMachineEntityModel) {
	state.NewSize = applyDefaultIfEmptyGeneric(state.NewSize, state.DefaultSize)
}

// apply current values to new values if action/stat projected value is not available
func setCurrentAzurermLinuxVirtualMachineToNewState(state *AzurermLinuxVirtualMachineEntityModel) {
	state.NewSize = applyDefaultIfEmptyGeneric(state.NewSize, state.CurrentSize)
}
