// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.
// This file will be overwritten by the generator.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type AzurermManagedDiskEntityModel struct {
	EntityUuid                types.String `tfsdk:"entity_uuid"`
	EntityName                types.String `tfsdk:"entity_name"`
	VendorId                  types.String `tfsdk:"vendor_id"`
	EntityType                types.String `tfsdk:"entity_type"`
	CurrentStorageAccountType types.String `tfsdk:"current_storage_account_type"`
	NewStorageAccountType     types.String `tfsdk:"new_storage_account_type"`
	DefaultStorageAccountType types.String `tfsdk:"default_storage_account_type"`
	CurrentDiskIopsReadWrite  types.Int64  `tfsdk:"current_disk_iops_read_write"`
	NewDiskIopsReadWrite      types.Int64  `tfsdk:"new_disk_iops_read_write"`
	DefaultDiskIopsReadWrite  types.Int64  `tfsdk:"default_disk_iops_read_write"`
	CurrentDiskMbpsReadWrite  types.Int64  `tfsdk:"current_disk_mbps_read_write"`
	NewDiskMbpsReadWrite      types.Int64  `tfsdk:"new_disk_mbps_read_write"`
	DefaultDiskMbpsReadWrite  types.Int64  `tfsdk:"default_disk_mbps_read_write"`
	CurrentDiskSizeGb         types.Int64  `tfsdk:"current_disk_size_gb"`
	NewDiskSizeGb             types.Int64  `tfsdk:"new_disk_size_gb"`
	DefaultDiskSizeGb         types.Int64  `tfsdk:"default_disk_size_gb"`
}

type AzurermManagedDiskDataSource struct {
	client *turboclient.Client
}

func NewAzurermManagedDiskDataSource() datasource.DataSource {
	return &AzurermManagedDiskDataSource{}
}

func (d *AzurermManagedDiskDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azurerm_managed_disk"
}

func (d *AzurermManagedDiskDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_azurerm_managed_disk` data source.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the Azure Managed Disk entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the Azure Managed Disk entity. This field is used for search operations when a valid vendor_id is not provided",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"vendor_id": schema.StringAttribute{
				MarkdownDescription: "id of the Azure Managed Disk entity. When provided, this field is used as the primary search criteria, taking precedence over entity_name",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the Azure Managed Disk entity",
				Computed:            true,
			},

			"current_storage_account_type": schema.StringAttribute{
				MarkdownDescription: "current storage type of the Azure Managed Disk entity",
				Computed:            true,
			},

			"new_storage_account_type": schema.StringAttribute{
				MarkdownDescription: "recommended storage type of the Azure Managed Disk entity",
				Computed:            true,
			},

			"default_storage_account_type": schema.StringAttribute{
				MarkdownDescription: "default storage type of the Azure Managed Disk entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("Standard_LRS", "StandardSSD_LRS", "Premium_LRS", "UltraSSD_LRS", "PremiumV2_LRS", "StandardSSD_ZRS"),
				},
			},

			"current_disk_iops_read_write": schema.Int64Attribute{
				MarkdownDescription: "current IOPS of the volume entity, update is only valid for UltraSSD disks and PremiumV2 disks",
				Computed:            true,
			},

			"new_disk_iops_read_write": schema.Int64Attribute{
				MarkdownDescription: "recommended IOPS of the volume entity, update is only valid for UltraSSD disks and PremiumV2 disks",
				Computed:            true,
			},

			"default_disk_iops_read_write": schema.Int64Attribute{
				MarkdownDescription: "default IOPS of the volume entity, update is only valid for UltraSSD disks and PremiumV2 disks",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},

			"current_disk_mbps_read_write": schema.Int64Attribute{
				MarkdownDescription: "current throughput of the volume entity in MiB/s",
				Computed:            true,
			},

			"new_disk_mbps_read_write": schema.Int64Attribute{
				MarkdownDescription: "recommended throughput of the volume entity in MiB/s",
				Computed:            true,
			},

			"default_disk_mbps_read_write": schema.Int64Attribute{
				MarkdownDescription: "default throughput of the volume entity in MiB/s",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},

			"current_disk_size_gb": schema.Int64Attribute{
				MarkdownDescription: "current size of the volume entity in GiB",
				Computed:            true,
			},

			"new_disk_size_gb": schema.Int64Attribute{
				MarkdownDescription: "recommended size of the volume entity in GiB",
				Computed:            true,
			},

			"default_disk_size_gb": schema.Int64Attribute{
				MarkdownDescription: "default size of the volume entity in GiB",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
		},
	}
}

func (d *AzurermManagedDiskDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.RequiredTogether(
			path.MatchRoot("default_storage_account_type"),
			path.MatchRoot("default_disk_iops_read_write"),
			path.MatchRoot("default_disk_mbps_read_write"),
			path.MatchRoot("default_disk_size_gb"),
		),
		datasourcevalidator.AtLeastOneOf(
			path.MatchRoot("entity_name"), path.MatchRoot("vendor_id"),
		),
	}
}

func (d *AzurermManagedDiskDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected: *turboclient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *AzurermManagedDiskDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state AzurermManagedDiskEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("VirtualVolume")
	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()

	if d.client == nil {
		// set new values with default values, if client is unset/unreachable
		setDefaultsAzurermManagedDiskToNewState(&state)
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	var entity turboclient.SearchResults
	var errDiag *diag.ErrorDiagnostic
	entityArgs := []EntityOptionWithVendorId{
		WithVendorId(state.VendorId.ValueString()),
		WithEntityTypeForVendorId(enTyp),
	}
	entity, errDiag = GetEntitiesByVendorId(d.client, entityArgs...)
	if errDiag != nil {
		errDetail := fmt.Sprintf("Entity %s not found in Turbonomic instance when searching by vendor id, searching without it", enName)
		tflog.Warn(ctx, errDetail)

		entityArgs := []EntityOption{
			WithEntityName(enName),
			WithEntityType(enTyp),
			WithEnvironmentType("CLOUD"),
			WithCloudType("AZURE"),
		}
		entity, errDiag = GetEntitiesByName(d.client, entityArgs...)
	}

	var err error
	var errDetail string
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(entity) == 0 {
		errDetail = fmt.Sprintf("entity %s of type %s not found in Turbonomic instance", enName, enTyp)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("entity id found: %s\n", entity[0].UUID))
		state.EntityUuid = types.StringValue(entity[0].UUID)
		state, err = HandleAzurermManagedDiskCurrentState(ctx, state, entity)
		if err != nil {
			errDetail = fmt.Sprintf("error while trying to retrieve current value, %s", err.Error())
		}
	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an entity", errDetail)

		// if entity doesn't exist or got an error while retrieving entity using API, update new values with default values
		setDefaultsAzurermManagedDiskToNewState(&state)
		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}
	// as stat returns current value as projected when there are no action, calling it before  checking action to ensure data is available
	commodityActions, errDiag := GetStatsByEntityUUIDAndType(d.client, entity[0].UUID, "VirtualVolume")
	if errDiag != nil {
		tflog.Warn(ctx, errDiag.Detail())
		resp.Diagnostics.AddWarning(errDiag.Summary(), errDiag.Detail())
		return
	}

	// use the extracted function to handle commodity actions
	if err := HandleAzurermManagedDiskCommodityAction(ctx, commodityActions, &state); err != nil {
		tflog.Warn(ctx, err.Error())
		resp.Diagnostics.AddWarning("error while processing commodity actions", err.Error())
		return
	}

	actions, errDiag := GetActions(d.client, WithEntityUuid(entity[0].UUID), WithActionTypes([]string{"SCALE"}))
	errDetail = ""
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(actions) == 0 {
		errDetail = fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("action id found: %d\n", actions[0].ActionID))
		state, err = HandleAzurermManagedDiskAction(ctx, resp, state, actions)
		if err != nil {
			errDetail = fmt.Sprintf("error while trying to retrieve new value, %s", err.Error())
		}
	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an action", errDetail)

		// if action doesn't exist or got an error while retrieving entity action using API, update new with current value
		setCurrentAzurermManagedDiskToNewState(&state)
		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
		}
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsAzurermManagedDiskToCurrentState(&state)
	setDefaultsAzurermManagedDiskToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// set the current state fields with default values if they are empty
func setDefaultsAzurermManagedDiskToCurrentState(state *AzurermManagedDiskEntityModel) {
	state.CurrentStorageAccountType = applyDefaultIfEmptyGeneric(state.CurrentStorageAccountType, state.DefaultStorageAccountType)
	state.CurrentDiskIopsReadWrite = applyDefaultIfEmptyGeneric(state.CurrentDiskIopsReadWrite, state.DefaultDiskIopsReadWrite)
	state.CurrentDiskMbpsReadWrite = applyDefaultIfEmptyGeneric(state.CurrentDiskMbpsReadWrite, state.DefaultDiskMbpsReadWrite)
	state.CurrentDiskSizeGb = applyDefaultIfEmptyGeneric(state.CurrentDiskSizeGb, state.DefaultDiskSizeGb)
}

// set the new state fields with default values if they are empty
func setDefaultsAzurermManagedDiskToNewState(state *AzurermManagedDiskEntityModel) {
	state.NewStorageAccountType = applyDefaultIfEmptyGeneric(state.NewStorageAccountType, state.DefaultStorageAccountType)
	state.NewDiskIopsReadWrite = applyDefaultIfEmptyGeneric(state.NewDiskIopsReadWrite, state.DefaultDiskIopsReadWrite)
	state.NewDiskMbpsReadWrite = applyDefaultIfEmptyGeneric(state.NewDiskMbpsReadWrite, state.DefaultDiskMbpsReadWrite)
	state.NewDiskSizeGb = applyDefaultIfEmptyGeneric(state.NewDiskSizeGb, state.DefaultDiskSizeGb)
}

// apply current values to new values if action/stat projected value is not available
func setCurrentAzurermManagedDiskToNewState(state *AzurermManagedDiskEntityModel) {
	state.NewStorageAccountType = applyDefaultIfEmptyGeneric(state.NewStorageAccountType, state.CurrentStorageAccountType)
	state.NewDiskIopsReadWrite = applyDefaultIfEmptyGeneric(state.NewDiskIopsReadWrite, state.CurrentDiskIopsReadWrite)
	state.NewDiskMbpsReadWrite = applyDefaultIfEmptyGeneric(state.NewDiskMbpsReadWrite, state.CurrentDiskMbpsReadWrite)
	state.NewDiskSizeGb = applyDefaultIfEmptyGeneric(state.NewDiskSizeGb, state.CurrentDiskSizeGb)
}
