// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

// Not autogenerated as variables are different
type CloudEntityRecommendationEntityModel struct {
	EntityUuid  types.String `tfsdk:"entity_uuid"`
	EntityName  types.String `tfsdk:"entity_name"`
	EntityType  types.String `tfsdk:"entity_type"`
	CurrentSize types.String `tfsdk:"current_instance_type"`
	NewSize     types.String `tfsdk:"new_instance_type"`
	DefaultSize types.String `tfsdk:"default_size"`
}

type CloudEntityRecommendationDataSource struct {
	client *turboclient.Client
}

func NewCloudEntityRecommendationDataSource() datasource.DataSource {
	return &CloudEntityRecommendationDataSource{}
}

func (d *CloudEntityRecommendationDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cloud_entity_recommendation"
}

func (d *CloudEntityRecommendationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_cloud_entity_recommendation` data source. \n \n ~> **NOTE:** `turbonomic_cloud_entity_recommendation` data source has been deprecated in version 1.4.0 and will be removed in future versions.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the cloud entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the cloud entity",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the cloud entity",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOfCaseInsensitive("VirtualMachine", "VirtualVolume", "Database", "DatabaseServer"),
				},
			},

			"current_instance_type": schema.StringAttribute{
				MarkdownDescription: "current tier of the cloud entity",
				Computed:            true,
			},

			"new_instance_type": schema.StringAttribute{
				MarkdownDescription: "recommended tier of the cloud entity",
				Computed:            true,
			},

			"default_size": schema.StringAttribute{
				MarkdownDescription: "default tier of the cloud entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(20), stringvalidator.RegexMatches(regexp.MustCompile(`^[A-Za-z0-9._-]+$`), "must contain only alphanumeric, '.', '-', or '_' characters"),
				},
			},
		},
	}
}

func (d *CloudEntityRecommendationDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.RequiredTogether(
			path.MatchRoot("default_size"),
		),
	}
}

func (d *CloudEntityRecommendationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected: *turboclient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *CloudEntityRecommendationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state CloudEntityRecommendationEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)

	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()
	entity, errDiag := GetEntitiesByNameAndType(d.client, enName, enTyp, "CLOUD", "")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(entity) == 0 {
		errDetail := fmt.Sprintf("Entity %s of type %s not found in Turbonomic instance", enName, enTyp)
		tflog.Warn(ctx, errDetail)

		// if entity doesn't exist, update new values with default values
		state.NewSize = applyDefaultIfEmpty(
			state.NewSize,
			state.DefaultSize,
		)

		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Entity id found: %s\n", entity[0].UUID))
	state.EntityUuid = types.StringValue(entity[0].UUID)

	// sets current fields in state
	var err error
	state, err = HandleCloudEntityRecommendationCurrentState(ctx, state, entity)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for current value",
			err.Error(),
		)
		return
	}

	actions, errDiag := GetActionsByEntityUUIDAndType(d.client, entity[0].UUID, "SCALE")
	if errDiag != nil {
		tflog.Error(ctx, errDiag.Detail())
		resp.Diagnostics.AddError(errDiag.Summary(), errDiag.Detail())
		return
	} else if len(actions) == 0 {
		errDetail := fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
		tflog.Trace(ctx, errDetail)

		// if action doesn't exist, update new with default value
		state.NewSize = state.CurrentSize

		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
		}

		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Action id found: %d\n", actions[0].ActionID))

	state, err = HandleCloudEntityRecommendationAction(ctx, resp, state, actions)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unknown storage type for new value",
			err.Error(),
		)
		return
	}

	// update new and curr values with default values, if its still empty
	state.CurrentSize = applyDefaultIfEmpty(
		state.CurrentSize,
		state.DefaultSize,
	)
	state.NewSize = applyDefaultIfEmpty(
		state.NewSize,
		state.DefaultSize,
	)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddError("Error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
