// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.
// This file will be overwritten by the generator.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type GoogleComputeInstanceEntityModel struct {
	EntityUuid         types.String `tfsdk:"entity_uuid"`
	EntityName         types.String `tfsdk:"entity_name"`
	VendorId           types.String `tfsdk:"vendor_id"`
	EntityType         types.String `tfsdk:"entity_type"`
	CurrentMachineType types.String `tfsdk:"current_machine_type"`
	NewMachineType     types.String `tfsdk:"new_machine_type"`
	DefaultMachineType types.String `tfsdk:"default_machine_type"`
}

type GoogleComputeInstanceDataSource struct {
	client *turboclient.Client
}

func NewGoogleComputeInstanceDataSource() datasource.DataSource {
	return &GoogleComputeInstanceDataSource{}
}

func (d *GoogleComputeInstanceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_google_compute_instance"
}

func (d *GoogleComputeInstanceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_google_compute_instance` data source.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the Google Compute entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the Google Compute entity. This field is used for search operations when a valid vendor_id is not provided",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"vendor_id": schema.StringAttribute{
				MarkdownDescription: "id of the Google Compute entity. When provided, this field is used as the primary search criteria, taking precedence over entity_name",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the Google Compute entity",
				Computed:            true,
			},

			"current_machine_type": schema.StringAttribute{
				MarkdownDescription: "current machine type of the Google Compute entity",
				Computed:            true,
			},

			"new_machine_type": schema.StringAttribute{
				MarkdownDescription: "recommended machine type of the Google Compute entity",
				Computed:            true,
			},

			"default_machine_type": schema.StringAttribute{
				MarkdownDescription: "default machine type of the Google Compute entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
		},
	}
}

func (d *GoogleComputeInstanceDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.AtLeastOneOf(
			path.MatchRoot("entity_name"), path.MatchRoot("vendor_id"),
		),
	}
}

func (d *GoogleComputeInstanceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"unexpected data-source configure type",
			fmt.Sprintf("expected: *turboclient.Client, got: %T. please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *GoogleComputeInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state GoogleComputeInstanceEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("VirtualMachine")
	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()

	if d.client == nil {
		// set new values with default values, if client is unset/unreachable
		setDefaultsGoogleComputeInstanceToNewState(&state)
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	var entity turboclient.SearchResults
	var errDiag *diag.ErrorDiagnostic
	entityArgs := []EntityOptionWithVendorId{
		WithVendorId(state.VendorId.ValueString()),
		WithEntityTypeForVendorId(enTyp),
	}
	entity, errDiag = GetEntitiesByVendorId(d.client, entityArgs...)
	if len(entity) == 0 || errDiag != nil {
		if errDiag != nil {
			tflog.Debug(ctx, fmt.Sprintf("error while searching by vendor id: %s", errDiag.Detail()))
		}

		errDetail := fmt.Sprintf("entity %s not found in Turbonomic instance when searching by vendor id, searching without it", enName)
		tflog.Warn(ctx, errDetail)

		entityArgs := []EntityOption{
			WithEntityName(enName),
			WithEntityType(enTyp),
			WithEnvironmentType("CLOUD"),
			WithCloudType("GCP"),
			ShowVendorIdString(true),
		}
		entity, errDiag = GetEntitiesByName(d.client, entityArgs...)
	}

	var err error
	var errDetail string
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(entity) == 0 {
		errDetail = fmt.Sprintf("entity %s of type %s not found in Turbonomic instance", enName, enTyp)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("entity id found: %s\n", entity[0].UUID))
		state.EntityUuid = types.StringValue(entity[0].UUID)
		state, err = HandleGoogleComputeInstanceCurrentState(ctx, state, entity)
		if err != nil {
			errDetail = fmt.Sprintf("error while trying to retrieve current value, %s", err.Error())
		}
	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an entity", errDetail)

		// if entity doesn't exist or got an error while retrieving entity using API, update new values with default values
		setDefaultsGoogleComputeInstanceToNewState(&state)
		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	actions, errDiag := GetActions(d.client, WithEntityUuid(entity[0].UUID), WithActionTypes([]string{"SCALE"}))
	errDetail = ""
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(actions) == 0 {
		errDetail = fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("action id found: %d\n", actions[0].ActionID))

		canExecute, executeMsg := canExecuteAction(actions)
		if canExecute {
			state, err = HandleGoogleComputeInstanceAction(ctx, resp, state, actions)
			if err != nil {
				errDetail = fmt.Sprintf("error while trying to retrieve new value, %s", err.Error())
			}
		} else {
			errDetail = executeMsg
		}

	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an action", errDetail)

		// if action doesn't exist or got an error while retrieving entity action using API, update new with current value
		setCurrentGoogleComputeInstanceToNewState(&state)
		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
		}
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsGoogleComputeInstanceToCurrentState(&state)
	setDefaultsGoogleComputeInstanceToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// set the current state fields with default values if they are empty
func setDefaultsGoogleComputeInstanceToCurrentState(state *GoogleComputeInstanceEntityModel) {
	state.CurrentMachineType = applyDefaultIfEmptyGeneric(state.CurrentMachineType, state.DefaultMachineType)
}

// set the new state fields with default values if they are empty
func setDefaultsGoogleComputeInstanceToNewState(state *GoogleComputeInstanceEntityModel) {
	state.NewMachineType = applyDefaultIfEmptyGeneric(state.NewMachineType, state.DefaultMachineType)
}

// apply current values to new values if action/stat projected value is not available
func setCurrentGoogleComputeInstanceToNewState(state *GoogleComputeInstanceEntityModel) {
	state.NewMachineType = applyDefaultIfEmptyGeneric(state.NewMachineType, state.CurrentMachineType)
}
