// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0
// Code generated by provider-code-generator; DO NOT EDIT.
// This file will be overwritten by the generator.

package provider

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	turboclient "github.com/IBM/turbonomic-go-client"
)

var (
	_ validator.String
	_ = stringvalidator.LengthAtLeast(1)
	_ = regexp.MustCompile(".*")
)

type GoogleComputeDiskEntityModel struct {
	EntityUuid                   types.String `tfsdk:"entity_uuid"`
	EntityName                   types.String `tfsdk:"entity_name"`
	VendorId                     types.String `tfsdk:"vendor_id"`
	EntityType                   types.String `tfsdk:"entity_type"`
	CurrentType                  types.String `tfsdk:"current_type"`
	NewType                      types.String `tfsdk:"new_type"`
	DefaultType                  types.String `tfsdk:"default_type"`
	CurrentProvisionedIops       types.Int64  `tfsdk:"current_provisioned_iops"`
	NewProvisionedIops           types.Int64  `tfsdk:"new_provisioned_iops"`
	DefaultProvisionedIops       types.Int64  `tfsdk:"default_provisioned_iops"`
	CurrentProvisionedThroughput types.Int64  `tfsdk:"current_provisioned_throughput"`
	NewProvisionedThroughput     types.Int64  `tfsdk:"new_provisioned_throughput"`
	DefaultProvisionedThroughput types.Int64  `tfsdk:"default_provisioned_throughput"`
	CurrentSize                  types.Int64  `tfsdk:"current_size"`
	NewSize                      types.Int64  `tfsdk:"new_size"`
	DefaultSize                  types.Int64  `tfsdk:"default_size"`
}

type GoogleComputeDiskDataSource struct {
	client *turboclient.Client
}

func NewGoogleComputeDiskDataSource() datasource.DataSource {
	return &GoogleComputeDiskDataSource{}
}

func (d *GoogleComputeDiskDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_google_compute_disk"
}

func (d *GoogleComputeDiskDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The following example demonstrates the syntax for the `turbonomic_google_compute_disk` data source.",
		Attributes: map[string]schema.Attribute{

			"entity_uuid": schema.StringAttribute{
				MarkdownDescription: "Turbonomic UUID of the virtual volume entity",
				Computed:            true,
			},

			"entity_name": schema.StringAttribute{
				MarkdownDescription: "name of the Google cloud volume entity. This field is used for search operations when a valid vendor_id is not provided",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"vendor_id": schema.StringAttribute{
				MarkdownDescription: "self_link of the Google cloud volume entity. When provided, this field is used as the primary search criteria, taking precedence over entity_name",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},

			"entity_type": schema.StringAttribute{
				MarkdownDescription: "type of the virtual volume entity",
				Computed:            true,
			},

			"current_type": schema.StringAttribute{
				MarkdownDescription: "current tier of the virtual volume entity",
				Computed:            true,
			},

			"new_type": schema.StringAttribute{
				MarkdownDescription: "recommended tier of the virtual volume entity",
				Computed:            true,
			},

			"default_type": schema.StringAttribute{
				MarkdownDescription: "default tier of the virtual volume entity",
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOfCaseInsensitive("pd-standard", "pd-balanced", "pd-ssd", "pd-extreme", "hyperdisk-balanced", "hyperdisk-throughput", "hyperdisk-extreme"),
				},
			},

			"current_provisioned_iops": schema.Int64Attribute{
				MarkdownDescription: "current IOPS of the volume entity, update is only supported by hyperdisk skus",
				Computed:            true,
			},

			"new_provisioned_iops": schema.Int64Attribute{
				MarkdownDescription: "recommended IOPS of the volume entity, update is only supported by hyperdisk skus",
				Computed:            true,
			},

			"default_provisioned_iops": schema.Int64Attribute{
				MarkdownDescription: "default IOPS of the volume entity, update is only supported by hyperdisk skus",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},

			"current_provisioned_throughput": schema.Int64Attribute{
				MarkdownDescription: "current throughput of the volume entity in MiB/s, update is only supported by hyperdisk skus",
				Computed:            true,
			},

			"new_provisioned_throughput": schema.Int64Attribute{
				MarkdownDescription: "recommended throughput of the volume entity in MiB/s, update is only supported by hyperdisk skus",
				Computed:            true,
			},

			"default_provisioned_throughput": schema.Int64Attribute{
				MarkdownDescription: "default throughput of the volume entity in MiB/s, update is only supported by hyperdisk skus",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},

			"current_size": schema.Int64Attribute{
				MarkdownDescription: "current size of the volume entity in GiB",
				Computed:            true,
			},

			"new_size": schema.Int64Attribute{
				MarkdownDescription: "recommended size of the volume entity in GiB",
				Computed:            true,
			},

			"default_size": schema.Int64Attribute{
				MarkdownDescription: "default size of the volume entity in GiB",
				Optional:            true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
		},
	}
}

func (d *GoogleComputeDiskDataSource) ConfigValidators(ctx context.Context) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		GoogleComputeDiskValidator{},
		datasourcevalidator.AtLeastOneOf(
			path.MatchRoot("entity_name"), path.MatchRoot("vendor_id"),
		),
	}
}

func (d *GoogleComputeDiskDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*turboclient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("expected: *turboclient.Client, got: %T. please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *GoogleComputeDiskDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state GoogleComputeDiskEntityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	state.EntityType = types.StringValue("VirtualVolume")
	enName, enTyp := state.EntityName.ValueString(), state.EntityType.ValueString()

	if d.client == nil {
		// set new values with default values, if client is unset/unreachable
		setDefaultsGoogleComputeDiskToNewState(&state)
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	var entity turboclient.SearchResults
	var errDiag *diag.ErrorDiagnostic
	entityArgs := []EntityOptionWithVendorId{
		WithVendorId(state.VendorId.ValueString()),
		WithEntityTypeForVendorId(enTyp),
	}
	entity, errDiag = GetEntitiesByVendorId(d.client, entityArgs...)
	if len(entity) == 0 || errDiag != nil {
		if errDiag != nil {
			tflog.Debug(ctx, fmt.Sprintf("error while searching by vendor id: %s", errDiag.Detail()))
		}

		errDetail := fmt.Sprintf("entity %s not found in Turbonomic instance when searching by vendor id, searching without it", enName)
		tflog.Warn(ctx, errDetail)

		entityArgs := []EntityOption{
			WithEntityName(enName),
			WithEntityType(enTyp),
			WithEnvironmentType("CLOUD"),
			WithCloudType("GCP"),
			ShowVendorIdString(true),
		}
		entity, errDiag = GetEntitiesByName(d.client, entityArgs...)
	}

	var err error
	var errDetail string
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(entity) == 0 {
		errDetail = fmt.Sprintf("entity %s of type %s not found in Turbonomic instance", enName, enTyp)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("entity id found: %s\n", entity[0].UUID))
		state.EntityUuid = types.StringValue(entity[0].UUID)
		state, err = HandleGoogleComputeDiskCurrentState(ctx, state, entity)
		if err != nil {
			errDetail = fmt.Sprintf("error while trying to retrieve current value, %s", err.Error())
		}
	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an entity", errDetail)

		// if entity doesn't exist or got an error while retrieving entity using API, update new values with default values
		setDefaultsGoogleComputeDiskToNewState(&state)
		state.EntityType = types.StringNull()
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}
	// as stat returns current value as projected when there are no action, calling it before  checking action to ensure data is available
	commodityActions, errDiag := GetStatsByEntityUUIDAndType(d.client, entity[0].UUID, "VirtualVolume")
	if errDiag != nil {
		tflog.Warn(ctx, errDiag.Detail())
		resp.Diagnostics.AddWarning(errDiag.Summary(), errDiag.Detail())
		return
	}

	// use the extracted function to handle commodity actions
	if err := HandleGoogleComputeDiskCommodityAction(ctx, commodityActions, &state); err != nil {
		tflog.Warn(ctx, err.Error())
		resp.Diagnostics.AddWarning("error while processing commodity actions", err.Error())
		return
	}

	actions, errDiag := GetActions(d.client, WithEntityUuid(entity[0].UUID), WithActionTypes([]string{"SCALE"}))
	errDetail = ""
	if errDiag != nil {
		errDetail = errDiag.Detail()
	} else if len(actions) == 0 {
		errDetail = fmt.Sprintf("no matching action found for entity id: %s", entity[0].UUID)
	} else {
		tflog.Debug(ctx, fmt.Sprintf("action id found: %d\n", actions[0].ActionID))

		canExecute, executeMsg := canExecuteAction(actions)
		if canExecute {
			state, err = HandleGoogleComputeDiskAction(ctx, resp, state, actions)
			if err != nil {
				errDetail = fmt.Sprintf("error while trying to retrieve new value, %s", err.Error())
			}
		} else {
			errDetail = executeMsg
		}

	}
	if len(errDetail) != 0 {
		tflog.Warn(ctx, errDetail)
		resp.Diagnostics.AddWarning("error while getting an action", errDetail)

		// if action doesn't exist or got an error while retrieving entity action using API, update new with current value
		setCurrentGoogleComputeDiskToNewState(&state)
		if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
			resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
		}
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
		return
	}

	// update new and curr values with default values, if its still empty
	setDefaultsGoogleComputeDiskToCurrentState(&state)
	setDefaultsGoogleComputeDiskToNewState(&state)

	if err := TagEntity(d.client, state.EntityUuid.ValueString()); err != nil {
		resp.Diagnostics.AddWarning("error while tagging an entity", err.Error())
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// set the current state fields with default values if they are empty
func setDefaultsGoogleComputeDiskToCurrentState(state *GoogleComputeDiskEntityModel) {
	state.CurrentType = applyDefaultIfEmptyGeneric(state.CurrentType, state.DefaultType)
	state.CurrentProvisionedIops = applyDefaultIfEmptyGeneric(state.CurrentProvisionedIops, state.DefaultProvisionedIops)
	state.CurrentProvisionedThroughput = applyDefaultIfEmptyGeneric(state.CurrentProvisionedThroughput, state.DefaultProvisionedThroughput)
	state.CurrentSize = applyDefaultIfEmptyGeneric(state.CurrentSize, state.DefaultSize)
}

// set the new state fields with default values if they are empty
func setDefaultsGoogleComputeDiskToNewState(state *GoogleComputeDiskEntityModel) {
	state.NewType = applyDefaultIfEmptyGeneric(state.NewType, state.DefaultType)
	state.NewProvisionedIops = applyDefaultIfEmptyGeneric(state.NewProvisionedIops, state.DefaultProvisionedIops)
	state.NewProvisionedThroughput = applyDefaultIfEmptyGeneric(state.NewProvisionedThroughput, state.DefaultProvisionedThroughput)
	state.NewSize = applyDefaultIfEmptyGeneric(state.NewSize, state.DefaultSize)
}

// apply current values to new values if action/stat projected value is not available
func setCurrentGoogleComputeDiskToNewState(state *GoogleComputeDiskEntityModel) {
	state.NewType = applyDefaultIfEmptyGeneric(state.NewType, state.CurrentType)
	state.NewProvisionedIops = applyDefaultIfEmptyGeneric(state.NewProvisionedIops, state.CurrentProvisionedIops)
	state.NewProvisionedThroughput = applyDefaultIfEmptyGeneric(state.NewProvisionedThroughput, state.CurrentProvisionedThroughput)
	state.NewSize = applyDefaultIfEmptyGeneric(state.NewSize, state.CurrentSize)
}
