// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by provider-code-generator

package provider

import (
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

const (
	googleVMConfig = `
	data "turbonomic_google_compute_instance" "test" {
		entity_name  = "%s"
		default_machine_type = "%s"
	}
	`
	googleVMConfigNoDefaultType = `
	data "turbonomic_google_compute_instance" "test" {
		entity_name  = "%s"
	}
	`
	googleVMDataSourceRef = "data.turbonomic_google_compute_instance.test"
	googleVMName          = "vm-test"
	googleVMCurrentType   = "e2-medium"
	googleVMDefaultType   = "t2d-standard-1"
	googleVMInvalidType   = "invalid@type#"
)

// Test for a valid entity
func TestGoogleComputeInstanceDataSourceWithValidEntity(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, googleVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, googleVMTestDataBaseDir, validVmActionRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagsRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagRespTestData))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "Valid VM recommendation",
			testEntity:          googleVMName,
			expectedEntityName:  googleVMName,
			expectedDefaultType: googleVMDefaultType,
			expectedCurrentType: googleVMCurrentType,
			expectedNewType:     googleVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(googleVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "default_machine_type", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "current_machine_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "new_machine_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Test for an invalid entity
func TestGoogleComputeInstanceDataSourceWithInvalidEntity(t *testing.T) {
	mockServer := createLocalServer(t, "[]", "", "", "")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedNewType     string
	}{
		{
			name:                "Empty VM search",
			testEntity:          googleVMName,
			expectedEntityName:  googleVMName,
			expectedDefaultType: googleVMDefaultType,
			expectedNewType:     googleVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(googleVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckNoResourceAttr(googleVMDataSourceRef, "entity_type"),
							resource.TestCheckNoResourceAttr(googleVMDataSourceRef, "current_machine_type"),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "new_machine_type", tc.expectedNewType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "default_machine_type", tc.expectedDefaultType),
						),
					},
				},
			})
		})
	}
}

// Test for an entity that has no actions
func TestGoogleComputeInstanceDataSourceWithNoAction(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, googleVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, emptyActionRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagsRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagRespTestData))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedDefaultType string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "Empty VM recommendation",
			testEntity:          googleVMName,
			expectedEntityName:  googleVMName,
			expectedDefaultType: googleVMDefaultType,
			expectedCurrentType: googleVMCurrentType,
			expectedNewType:     googleVMCurrentType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(googleVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "default_machine_type", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "current_machine_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "new_machine_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests when default_machine_type is not specified
func TestGoogleComputeInstanceDataSourceWithoutDefaultType(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, googleVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, googleVMTestDataBaseDir, validVmActionRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagsRespTestData),
		loadTestFile(t, entityTagTestDataBaseDir, entityTagRespTestData))
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
	}{
		{
			name:                "default_machine_type not specified",
			testEntity:          googleVMName,
			expectedEntityName:  googleVMName,
			expectedCurrentType: googleVMCurrentType,
			expectedNewType:     googleVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(googleVMConfigNoDefaultType, tc.testEntity),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "current_machine_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "new_machine_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests error while retrieving entity tags
func TestGoogleComputeInstanceDataSourceGetEntityTagsError(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, googleVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, googleVMTestDataBaseDir, validVmActionRespTestData),
		"",
		"")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	t.Run("Error while retrieving entity tags", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(googleVMConfig, googleVMName, googleVMDefaultType),
					ExpectError: regexp.MustCompile(`Unable to retrieve entity tags from Turbonomic`),
				},
			},
		})
	})
}

// Tests error while tagging an entity
func TestGoogleComputeInstanceDataSourceTagEntityError(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, googleVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, googleVMTestDataBaseDir, validVmActionRespTestData),
		"[]",
		"")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))

	t.Run("Error while tagging an entity", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(googleVMConfig, googleVMName, googleVMDefaultType),
					ExpectError: regexp.MustCompile(`Unable to tag an entity in Turbonomic`),
				},
			},
		})
	})
}

// Tests no error while tagging already tagged entity with discovered "optimized by" tag value
func TestGoogleComputeInstanceDataSourceTagEntityAlreadyTaggedDiscovered(t *testing.T) {
	mockServer := createLocalServer(t,
		loadTestFile(t, googleVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, googleVMTestDataBaseDir, validVmActionRespTestData),
		`[{"key": "turbonomic_optimized_by","values": ["turbonomic-terraform-provider"]}]`,
		"")
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
		expectedDefaultType string
	}{
		{
			name:                "No error while tagging already tagged entity",
			testEntity:          googleVMName,
			expectedEntityName:  googleVMName,
			expectedCurrentType: googleVMCurrentType,
			expectedNewType:     googleVMDefaultType,
			expectedDefaultType: googleVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(googleVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "default_machine_type", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "current_machine_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "new_machine_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests no error while tagging already tagged entity with not discovered "optimized by" tag value
func TestGoogleComputeInstanceDataSourceTagEntityAlreadyTaggedNotDiscovered(t *testing.T) {
	mockServer := createLocalServerWithResponse(t,
		loadTestFile(t, googleVMTestDataBaseDir, searchRespTestData),
		loadTestFile(t, googleVMTestDataBaseDir, validVmActionRespTestData),
		`[]`,
		Response{
			Message:    "Entity service RPC call failed to complete request: INVALID_ARGUMENT: Trying to insert a tag with a key that already exists: turbonomic_optimized_by",
			HttpStatus: http.StatusBadRequest})
	defer mockServer.Close()

	providerConfig := fmt.Sprintf(config, strings.TrimPrefix(mockServer.URL, "https://"))
	for _, tc := range []struct {
		name                string
		testEntity          string
		expectedEntityName  string
		expectedCurrentType string
		expectedNewType     string
		expectedDefaultType string
	}{
		{
			name:                "Error while tagging already tagged entity",
			testEntity:          googleVMName,
			expectedEntityName:  googleVMName,
			expectedCurrentType: googleVMCurrentType,
			expectedNewType:     googleVMDefaultType,
			expectedDefaultType: googleVMDefaultType,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
				Steps: []resource.TestStep{
					{
						Config: providerConfig + fmt.Sprintf(googleVMConfig, tc.testEntity, tc.expectedDefaultType),
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_name", tc.expectedEntityName),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "entity_type", vmEntityType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "default_machine_type", tc.expectedDefaultType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "current_machine_type", tc.expectedCurrentType),
							resource.TestCheckResourceAttr(googleVMDataSourceRef, "new_machine_type", tc.expectedNewType),
						),
					},
				},
			})
		})
	}
}

// Tests invalid characters in default_machine_type field
func TestGoogleComputeInstanceDataSourceInvalidTypeCharacters(t *testing.T) {
	t.Run("Invalid characters in default_machine_type", func(t *testing.T) {
		resource.Test(t, resource.TestCase{
			ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:      providerConfig + fmt.Sprintf(googleVMConfig, googleVMName, googleVMInvalidType),
					ExpectError: regexp.MustCompile(`Invalid Attribute Value Match`),
				},
			},
		})
	})
}
