// Copyright (c) IBM Corporation
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by provider-code-generator
// All the helper functions used in handler files should be defined here

package provider

import (
	"math"
	"strings"
)

// nullableAttr is satisfied by types.String, types.Bool, types.Int64, types.Float64, etc.
// The extract function is passed separately because the Terraform framework uses concrete
// method names (ValueString, ValueBool, …) rather than a shared interface.
type nullableAttr[T any] interface {
	IsNull() bool
	IsUnknown() bool
}

// setIfKnown assigns *dest to extract(src) when src is non-null and non-unknown.
// It replaces the repeated pattern:
//
//	if !plan.Foo.IsNull() && !plan.Foo.IsUnknown() {
//	    v := plan.Foo.ValueXxx()
//	    dest = &v
//	}
func setIfKnown[T any, S nullableAttr[T]](dest **T, src S, extract func(S) T) {
	if !src.IsNull() && !src.IsUnknown() {
		v := extract(src)
		*dest = &v
	}
}

const (
	// Tag key and value for "optimized by" tag
	OptimizedByTagName       = "turbonomic_optimized_by"
	OptimizedByTagValue      = "turbonomic-terraform-provider"
	TagAlreadyExistsErrorMsg = "INVALID_ARGUMENT: Trying to insert a tag with a key that already exists: turbonomic_optimized_by"
)

// convertKbitToMiBps converts a value from Kibit/sec to MiB/sec and rounds the result
func convertKibitToMiBps(value float64) float64 {
	return math.Round(value / 8192)
}

// convertMBtoGiB converts a value from MB to GiB and rounds to the nearest integer
func convertMiBtoGiB(value float64) int64 {
	return int64(math.Round(value / 1024))
}

// convertSliceToUppercase converts a slice os strings to uppercase
func convertSliceToUppercase(values []string) []string {
	for i, value := range values {
		values[i] = strings.ToUpper(value)
	}
	return values
}

// ptrToString safely dereferences a *string for use in log messages.
// Returns an empty string when the pointer is nil.
func ptrToString(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// ptrToBool safely dereferences a *bool for use in log messages.
// Returns false when the pointer is nil.
func ptrToBool(b *bool) bool {
	if b == nil {
		return false
	}
	return *b
}
